-- seed.sql · client/src/data/reviews.js 12건 이관(문안 그대로 · mock=true).
-- 멱등: id 고정('rv-01'..) + ON CONFLICT DO NOTHING.
INSERT INTO reviews (id, user_id, author_label, country, course_label_key, rating, title, body, lang, mock, seed_likes, created_at)
VALUES
('rv-01', NULL, 'S.W.', '{"en":"United Kingdom","ko":"영국","th":"สหราชอาณาจักร"}'::jsonb, 'reviews.course.lunchDinner2act', 5, 'The pre-order actually works', 'Our dakgalbi at Tongnamujip was already on the grill when the van pulled up. We walked the Soyanggang Skywalk with no rush because the driver kept our two hour slot. Booking in English was the part I appreciated most.', 'en', true, 24, '2026-05-14T12:00:00+09:00'),
('rv-02', NULL, 'H.K.', '{"en":"South Korea","ko":"대한민국","th":"เกาหลีใต้"}'::jsonb, 'reviews.course.lunchCafeAct', 4, '부모님과 다녀온 하루', '부모님 모시고 택시형으로 다녀왔어요. 감자밭 감자빵을 미리 주문해 둔 덕분에 줄을 안 섰습니다. 소양강댐 전망은 좋았는데 바람이 많이 부니 겉옷을 챙기세요.', 'ko', true, 18, '2026-06-02T12:00:00+09:00'),
('rv-03', NULL, 'N.P.', '{"en":"Thailand","ko":"태국","th":"ไทย"}'::jsonb, 'reviews.course.lunchDinner2act', 5, 'จองง่าย เที่ยวสนุก', 'จองเป็นภาษาไทยได้จริง คนขับใจดีมาก มื้อกลางวันที่ Tongnamujip อร่อย และพายแคนูที่ Jungdo Mullegil สนุกที่สุด เวลาสองชั่วโมงต่อจุดกำลังพอดี', 'th', true, 31, '2026-04-21T12:00:00+09:00'),
('rv-04', NULL, 'T.M.', '{"en":"Japan","ko":"일본","th":"ญี่ปุ่น"}'::jsonb, 'reviews.course.lunch2act', 4, '初めての春川、快適でした', '初めての春川でしたが、車で回れたので楽でした。マッククス体験博物館で麺作りをして、公池川をゆっくり散歩。昼食の予約が済んでいたのは助かりました。', 'ja', true, 12, '2026-03-18T12:00:00+09:00'),
('rv-05', NULL, 'J.R.', '{"en":"Australia","ko":"호주","th":"ออสเตรเลีย"}'::jsonb, 'reviews.course.none2act', 3, 'Good for groups, plan for winter', 'Good value for a group of five in the van. The Art Circle workshop was the highlight. The two hour slots felt a bit long at Gongjicheon in winter, so I would pick different stops in cold months.', 'en', true, 7, '2026-02-27T12:00:00+09:00'),
('rv-06', NULL, 'L.W.', '{"en":"China","ko":"중국","th":"จีน"}'::jsonb, 'reviews.course.lunchDinnerMix', 5, '按自己的节奏玩春川', '行程按我们选的顺序走，司机每一站都准时。通木屋鸡排提前点好了，到店就能吃。Soul Roastery 的咖啡很好，湖上的天空步道也值得去。', 'zh', true, 27, '2026-05-30T12:00:00+09:00'),
('rv-07', NULL, 'C.G.', '{"en":"Spain","ko":"스페인","th":"สเปน"}'::jsonb, 'reviews.course.lunchDinner2act', 4, 'Un día completo sin estrés', 'Reservamos todo desde el móvil sin hablar coreano. La comida en Tongnamujip llegó rápida porque ya estaba pedida. El paseo en canoa por Jungdo Mullegil fue lo mejor del día.', 'es', true, 15, '2026-06-15T12:00:00+09:00'),
('rv-08', NULL, 'D.K.', '{"en":"Canada","ko":"캐나다","th":"แคนาดา"}'::jsonb, 'reviews.course.lunch2act', 2, 'Nice day, book a weekday', 'The day itself was fine but our taxi arrived about ten minutes late and the Skywalk was crowded on a Saturday. The schedule still worked because the slots have slack. I would book a weekday next time.', 'en', true, 4, '2026-01-25T12:00:00+09:00'),
('rv-09', NULL, 'J.P.', '{"en":"South Korea","ko":"대한민국","th":"เกาหลีใต้"}'::jsonb, 'reviews.course.lunchDinnerMix', 5, '저녁까지 착착 진행돼요', '친구 넷이서 밴으로 하루를 꽉 채웠어요. 화동2571에서 쉬어 가는 코스로 짰는데 동선이 겹치지 않아서 좋았습니다. 저녁까지 미리 주문돼 있으니 기다림이 없네요.', 'ko', true, 33, '2026-06-28T12:00:00+09:00'),
('rv-10', NULL, 'K.S.', '{"en":"Japan","ko":"일본","th":"ญี่ปุ่น"}'::jsonb, 'reviews.course.lunchCafeAct', 5, '身軽に回れる一日', 'ソウルロースタリーのコーヒーと昭陽江スカイウォークの組み合わせが良かったです。荷物を預けられたので身軽に回れました。チケットの画面を見せるだけで乗車できます。', 'ja', true, 20, '2026-04-05T12:00:00+09:00'),
('rv-11', NULL, 'A.B.', '{"en":"Germany","ko":"독일","th":"เยอรมนี"}'::jsonb, 'reviews.course.none2act', 4, 'Simple and predictable', 'We skipped the meal plan and just did the Soyang River Dam and the Soyanggang Maiden Statue. The driver waited at each stop as promised. Simple, predictable, and cheaper than chartering a car ourselves.', 'en', true, 9, '2026-03-09T12:00:00+09:00'),
('rv-12', NULL, 'S.C.', '{"en":"Thailand","ko":"태국","th":"ไทย"}'::jsonb, 'reviews.course.lunch2act', 3, 'ดีแต่คนเยอะช่วงวันหยุด', 'โดยรวมดี รถสะอาดและตรงเวลา อาหารกลางวันอร่อย แต่พิพิธภัณฑ์มักกุกซูคนเยอะช่วงสุดสัปดาห์ อยากให้มีรอบเช้ากว่านี้', 'th', true, 6, '2026-05-08T12:00:00+09:00')
ON CONFLICT (id) DO NOTHING;
